### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/smail-data/jaad_train_16_16_n.csv'

### ISSUE THREAD

**Issue by OSU-Haolin** [Smail8/Pedestrian-Intention-Prediction-A-Muti-Task-Perspective#1]
When I run train.py, it shows the error as titele.
How to create /data/smail-data/jaad_train_16_16_n.csv

**Comment by Smail8** [comment]
Hi there,
Thank you for your interest in our work. Normally you should download the [JAAD dataset] (http://data.nvision2.eecs.yorku.ca/JAAD_dataset/), you can skip downloading the video clips if you are not interested in using scene data. Then you just need to follow the processing steps described in the dataset [repository](https://github.com/ykotseruba/JAAD).

I understand all this can be painful and time consuming so I've uploaded the processed data in a google [drive](
https://drive.google.com/drive/folders/1yi6jVxNfKJtbCQHNmzrHjVrrhR_orRJe?usp=sharing) for you.

Also, you need to modify the code in order to adapt the paths to data files:

- Under **args.jaad_dataset** you should put the path to the processed jaad annotations (annotation directory should have two directories one named 'train' and the other named 'val')

- You should set **args.from_file** to False, the transformation of data into sequences takes time, so we save the processed data into a csv file to avoid waiting each time we run training or testing. However, you still need to run the processing the first time, this is how '/data/smail-data/jaad_train_16_16_n.csv' is created.

- Set **args.save_path** to where you want the csv file to be saved

- Set **args.model_path** to where you want your trained model to be saved

Please let me know if you have any other issues.

**Comment by OSU-Haolin** [comment]
Thanks very much!
This project gives a good topic and baseline for me to start my research on pedestrian intention estimation.

I followed your steps and I met:
File "/home/haolin/CITR/JAAD/Pedestrian-Intention-Prediction-A-Muti-Task-Perspective/DataLoader.py", line 81, in __init__
    STRIDE = args.stride
AttributeError: 'args' object has no attribute 'stride'

Please check that there is no definition of "stride" in train.py.

Sincerely, 
Haolin

**Comment by OSU-Haolin** [comment]
> Thanks very much!
> This project gives a good topic and baseline for me to start my research on pedestrian intention estimation.
> 
> I followed your steps and I met:
> File "/home/haolin/CITR/JAAD/Pedestrian-Intention-Prediction-A-Muti-Task-Perspective/DataLoader.py", line 81, in **init**
> STRIDE = args.stride
> AttributeError: 'args' object has no attribute 'stride'
> 
> Please check that there is no definition of "stride" in train.py.
> 
> Sincerely,
> Haolin

I added "self.stride = 1" in train.py. Is it right for your project?

**Comment by Smail8** [comment]
Sorry for the late answer. 
I have noticed the errors. This repository is not maintained. Please refer to the official [repository ](https://github.com/vita-epfl/bounding-box-prediction) for the correct code as well as the trained model.  Also if you have other issues please post them on that repo.
For some reason this repo is more popular that the official one. I will be deleting it soon to give you time to read this answer.

I also added to the official repo a python script to process data directly from the original JAAD dataset.

To answer your question, args.stride defines by how much the sliding window moves while creating sequences. It sets the overlap between sequences. Setting it to 1 would result in too much repetitive sequences since the frame rate is 30.
If you want no overlap at all you should set it to the same value as the sequence length, if you want a 50% overlap set it to half the sequence length. During my experiments I used 50% overlaps.
